### ISSUE TITLE
I request the using example of the library

### ISSUE THREAD

**Issue by ghost** [Tai-Min/Servo-for-Atmega328p#1]
this library usually be used by the beginners but I think there are no instructions for this library.

I tried below code and didn't work :

myServo.activate(PORTB,PINB2,180);

**Comment by ghost** [comment]
> this library usually be used by the beginners but I think there are no instructions for this library.
> 
> 
> 
> I tried below code and didn't work :
> 
> 
> 
> myServo.activate(PORTB,PINB2,180);



I edited library by my own and now it works.

original library couldnt compiled with many tries.

above code won't be compiled with atmel studio 7.

**Comment by Tai-Min** [comment]
Hello,

Sorry for late response.

This library wasn't meant to be used by beginners (by no one to be honest), it was my little project to deeply learn how microcontrollers work and also to get used to writting software directly for baremetal Atmega microcontrollers, without any third party HAL (such as Arduino).

I'm glad you've resolved your problem.

Regards,
Mateusz
